services:
  kostbaas:
    image: ghcr.io/notnoud/kostbaas:latest
    container_name: kostbaas
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      - DEBUG=false
