services:
  vaste-lasten:
    image: ghcr.io/notnoud/vaste-lasten:latest
    container_name: vaste-lasten
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      - DEBUG=false
